### ISSUE TITLE
Init  Error

### ISSUE THREAD

**Issue by skyonedot** [nameskyteam/namesky-sdk#14]
Hello, it seem that the sdk is not work? , the following is my code(just init `Namesky` Obejct), buy get error

```javascript
const { initNameSky, NameSkySigner, Amount, MultiSendAccount } = require('namesky-sdk');
const nearAPI = require("near-api-js");
const { keyStores, KeyPair } = nearAPI;
require('dotenv').config()
const {generateSeedPhrase } = require('near-seed-phrase') ;


async function main(){
    const myKeyStore = new keyStores.InMemoryKeyStore();
    let name = "nanshan.near"
    const keyPair = KeyPair.fromString(process.env.pk);
    let network = 'mainnet'

    // adds the keyPair you created to keyStore
    await myKeyStore.setKey(network, name, keyPair);
    const connectionConfig = {
        networkId: network,
        keyStore: myKeyStore , // first create a key store 
        nodeUrl: "https://rpc.mainnet.near.org",
        walletUrl: "https://wallet.near.org",
        helperUrl: "https://helper.near.org",
        explorerUrl: "https://explorer.near.org",
    };

    const connection = await nearAPI.connect(connectionConfig);
    // console.log(connection)
    console.log(connection.config.keyStore)


    const account = MultiSendAccount.new(connection, name);
    let signer = NameSkySigner.fromAccount(account)
    signer.network.networkId = "mainnet"
    // console.log(signer.network.networkId = "mainnet")
    const namesky = await initNameSky({ signer: signer});

}

main()
```

error is :
```
/root/Near/node_modules/.pnpm/namesky-sdk@5.9.2/node_modules/namesky-sdk/dist/core/NameSkySigner.js:20
                nodeUrl: this.sender.connection.provider.connection.url,
                                                         ^

TypeError: Cannot read properties of undefined (reading 'connection')
    at NameSkySigner.get network [as network] (/root/Near/node_modules/.pnpm/namesky-sdk@5.9.2/node_modules/namesky-sdk/dist/core/NameSkySigner.js:20:58)
    at initNameSky (/root/Near/node_modules/.pnpm/namesky-sdk@5.9.2/node_modules/namesky-sdk/dist/core/NameSky.js:291:30)
    at main (/root/Near/batchList.js:34:27)
```

the config is following:

```json
{
  "name": "near",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.6.7",
    "dotenv": "^16.4.5",
    "namesky-sdk": "^5.9.2",
    "near-api-js": "^4.0.0",
    "near-seed-phrase": "^0.2.0"
  }
}

```

**Comment by hanakannzashi** [comment]
`nearAPI.connect` return the `Near` object, you should use like:
```ts
const near = await nearAPI.connect(connectionConfig);
const account = MultiSendAccount.new(near.connection, name);
```

**Comment by hanakannzashi** [comment]
> Hello, it seem that the sdk is not work? , the following is my code(just init `Namesky` Obejct), buy get error
> 
> ```js
> const { initNameSky, NameSkySigner, Amount, MultiSendAccount } = require('namesky-sdk');
> const nearAPI = require("near-api-js");
> const { keyStores, KeyPair } = nearAPI;
> require('dotenv').config()
> const {generateSeedPhrase } = require('near-seed-phrase') ;
> 
> 
> async function main(){
>     const myKeyStore = new keyStores.InMemoryKeyStore();
>     let name = "nanshan.near"
>     const keyPair = KeyPair.fromString(process.env.pk);
>     let network = 'mainnet'
> 
>     // adds the keyPair you created to keyStore
>     await myKeyStore.setKey(network, name, keyPair);
>     const connectionConfig = {
>         networkId: network,
>         keyStore: myKeyStore , // first create a key store 
>         nodeUrl: "https://rpc.mainnet.near.org",
>         walletUrl: "https://wallet.near.org",
>         helperUrl: "https://helper.near.org",
>         explorerUrl: "https://explorer.near.org",
>     };
> 
>     const connection = await nearAPI.connect(connectionConfig);
>     // console.log(connection)
>     console.log(connection.config.keyStore)
> 
> 
>     const account = MultiSendAccount.new(connection, name);
>     let signer = NameSkySigner.fromAccount(account)
>     signer.network.networkId = "mainnet"
>     // console.log(signer.network.networkId = "mainnet")
>     const namesky = await initNameSky({ signer: signer});
> 
> }
> 
> main()
> ```
> 
> error is :
> 
> ```
> /root/Near/node_modules/.pnpm/namesky-sdk@5.9.2/node_modules/namesky-sdk/dist/core/NameSkySigner.js:20
>                 nodeUrl: this.sender.connection.provider.connection.url,
>                                                          ^
> 
> TypeError: Cannot read properties of undefined (reading 'connection')
>     at NameSkySigner.get network [as network] (/root/Near/node_modules/.pnpm/namesky-sdk@5.9.2/node_modules/namesky-sdk/dist/core/NameSkySigner.js:20:58)
>     at initNameSky (/root/Near/node_modules/.pnpm/namesky-sdk@5.9.2/node_modules/namesky-sdk/dist/core/NameSky.js:291:30)
>     at main (/root/Near/batchList.js:34:27)
> ```
> 
> the config is following:
> 
> ```json
> {
>   "name": "near",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "axios": "^1.6.7",
>     "dotenv": "^16.4.5",
>     "namesky-sdk": "^5.9.2",
>     "near-api-js": "^4.0.0",
>     "near-seed-phrase": "^0.2.0"
>   }
> }
> ```

`nearAPI.connect` return the `Near` object, you should use like:
```ts
const near = await nearAPI.connect(connectionConfig);
const account = MultiSendAccount.new(near.connection, name);
```

**Comment by skyonedot** [comment]
great, it had solved.
but there is new error about 
function `await namesky.postMint();` 

error show 
```
/root/Near/node_modules/namesky-sdk/node_modules/borsh/lib/index.js:323
        throw new BorshError(`Class ${obj.constructor.name} is missing in schema`);
              ^

BorshError: Class SignedTransaction is missing in schema
    at serializeStruct (/root/Near/node_modules/namesky-sdk/node_modules/borsh/lib/index.js:323:15)
    at serialize (/root/Near/node_modules/namesky-sdk/node_modules/borsh/lib/index.js:349:5)
    at encodeTransaction (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/transactions/lib/schema.js:33:34)
    at JsonRpcProvider.<anonymous> (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:76:64)
    at Generator.next (<anonymous>)
    at /root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:4:12)
    at JsonRpcProvider.sendTransaction (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:75:16)
    at MultiSendAccount.<anonymous> (/root/Near/node_modules/@near-js/accounts/lib/account.js:89:59) {
  fieldPath: [],
  originalMessage: 'Class SignedTransaction is missing in schema',
  context: ErrorContext {
    transactionHash: '3mkTNo8UhfNk2YjXPmfqYfzQqqpuP4RQN68a7xthLCxy'
  }
}
```


following code is 
```javascript
const { initNameSky, NameSkySigner, Amount, MultiSendAccount } = require('namesky-sdk');
const nearAPI = require("near-api-js");
const { keyStores, KeyPair } = nearAPI;
require('dotenv').config()
const {generateSeedPhrase } = require('near-seed-phrase') ;


async function main(){
    const myKeyStore = new keyStores.InMemoryKeyStore();
    let name = "nanshan.near"
    const keyPair = KeyPair.fromString(process.env.pk);
    let network = 'mainnet'

    // adds the keyPair you created to keyStore
    await myKeyStore.setKey(network, name, keyPair);
    const connectionConfig = {
        networkId: network,
        keyStore: myKeyStore , // first create a key store 
        nodeUrl: "https://rpc.mainnet.near.org",
        walletUrl: "https://wallet.near.org",
        helperUrl: "https://helper.near.org",
        explorerUrl: "https://explorer.near.org",
    };

    const connection = await nearAPI.connect(connectionConfig);
    // console.log(connection)
    // console.log(connection.config.keyStore)


    const account = MultiSendAccount.new(connection.connection, name);
    let signer = NameSkySigner.fromAccount(account)
    const namesky = await initNameSky({ signer: signer});

    await namesky.setRegistrantKey('9215.near', KeyPair.fromString('ed25519:'));
    await namesky.postMint('9215.near');
    
}

main()

```

**Comment by hanakannzashi** [comment]
> great, it had solved. but there is new error about function `await namesky.postMint();`
> 
> error show
> 
> ```
> /root/Near/node_modules/namesky-sdk/node_modules/borsh/lib/index.js:323
>         throw new BorshError(`Class ${obj.constructor.name} is missing in schema`);
>               ^
> 
> BorshError: Class SignedTransaction is missing in schema
>     at serializeStruct (/root/Near/node_modules/namesky-sdk/node_modules/borsh/lib/index.js:323:15)
>     at serialize (/root/Near/node_modules/namesky-sdk/node_modules/borsh/lib/index.js:349:5)
>     at encodeTransaction (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/transactions/lib/schema.js:33:34)
>     at JsonRpcProvider.<anonymous> (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:76:64)
>     at Generator.next (<anonymous>)
>     at /root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:4:12)
>     at JsonRpcProvider.sendTransaction (/root/Near/node_modules/namesky-sdk/node_modules/@near-js/providers/lib/json-rpc-provider.js:75:16)
>     at MultiSendAccount.<anonymous> (/root/Near/node_modules/@near-js/accounts/lib/account.js:89:59) {
>   fieldPath: [],
>   originalMessage: 'Class SignedTransaction is missing in schema',
>   context: ErrorContext {
>     transactionHash: '3mkTNo8UhfNk2YjXPmfqYfzQqqpuP4RQN68a7xthLCxy'
>   }
> }
> ```
> 
> following code is
> 
> ```js
> const { initNameSky, NameSkySigner, Amount, MultiSendAccount } = require('namesky-sdk');
> const nearAPI = require("near-api-js");
> const { keyStores, KeyPair } = nearAPI;
> require('dotenv').config()
> const {generateSeedPhrase } = require('near-seed-phrase') ;
> 
> 
> async function main(){
>     const myKeyStore = new keyStores.InMemoryKeyStore();
>     let name = "nanshan.near"
>     const keyPair = KeyPair.fromString(process.env.pk);
>     let network = 'mainnet'
> 
>     // adds the keyPair you created to keyStore
>     await myKeyStore.setKey(network, name, keyPair);
>     const connectionConfig = {
>         networkId: network,
>         keyStore: myKeyStore , // first create a key store 
>         nodeUrl: "https://rpc.mainnet.near.org",
>         walletUrl: "https://wallet.near.org",
>         helperUrl: "https://helper.near.org",
>         explorerUrl: "https://explorer.near.org",
>     };
> 
>     const connection = await nearAPI.connect(connectionConfig);
>     // console.log(connection)
>     // console.log(connection.config.keyStore)
> 
> 
>     const account = MultiSendAccount.new(connection.connection, name);
>     let signer = NameSkySigner.fromAccount(account)
>     const namesky = await initNameSky({ signer: signer});
> 
>     await namesky.setRegistrantKey('9215.near', KeyPair.fromString('ed25519:'));
>     await namesky.postMint('9215.near');
>     
> }
> 
> main()
> ```

Try to use `near-api-js@2.1.4`
